name: Build

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * *" # midnight daily

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build docker image

    steps:
      - uses: actions/checkout@v2
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      - run: docker buildx create --use
      - name: Build the image
        run: PLATFORMS=limux/arm64,linux/amd64 make
        env:
          DOCKER_BUILDKIT: 1
