name: Build

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * *" # midnight daily

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build docker image

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the image
        run: make
        env:
          PLATFORMS: linux/arm64,linux/amd64
          DOCKER_BUILDKIT: 1
      - name: Report build failure in Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # TODO: change to failure once proven to work
