name: Pre-release

# Prepares a new release of the build image.
# 
# To trigger it, simply change the CHANGELOG.md file, replacing the
# "Unreleased" header with the header with the new release's 
# version number.
#
# The workflow will automatically prepare a pull request to the `release` branch.
#

on:
  push:
    branches: [automate-prerelase]
  pull_request:

jobs:

  versions:
    runs-on: ubuntu-latest
    name: Get version numbers
    outputs:
      released-version: ${{ steps.current-release.outputs.result }}
      next-version: ${{ steps.next-release.outputs.output }}
    steps:
      - uses: actions/checkout@v2
      - name: read the current version from the release.yaml
        id: current-release
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.env.version' '.github/workflows/release.yaml'
      - name: read latest version from the changelog
        id: next-release
        uses: mattwynne/changelog-action@v1.2
        with:
          args: latest
  
  update-release-yaml:
    runs-on: ubuntu-latest
    name: Update release.yaml
    needs: versions
    if: needs.versions.outputs.released-version != needs.versions.outputs.next-version
    env:
      released_version: ${{ needs.versions.outputs.released-version }}
      next_version: ${{ needs.versions.outputs.next-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: mikefarah/yq@master
        with:
          cmd: yq eval '.env.version = "${{ env.next_version }}"' --inplace .github/workflows/release.yaml
      - run: cat .github/workflows/release.yaml
      - 
      - run: |
          git checkout main
          git add . && git commit -S -m "Prepare to release v$next_version"

  create-release-pr:
    runs-on: ubuntu-latest
    name: Create Release PR
    needs: update-release-yaml, versions
    if: needs.versions.outputs.released-version != needs.versions.outputs.next-version
    env:
      next_version: ${{ needs.versions.outputs.next-version }}
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Release ${{ env.next_version }}"
          branch: release/${{ env.next_version }}
          title: "Release ${{ env.next_version }}"
          body: |
            Automated changed by [pre-release.yaml](https://github.com/cucumber/build/blob/main/.github/workflows/pre-release.yaml) GitHub action.

            See diff for details.
          team-reviewers: @cucumber/build