name: Pre-release

on:
  push:
    branches: [automate-prerelase]
  pull_request:

jobs:
  update-release-yaml:
    runs-on: ubuntu-latest
    name: Update release.yaml

    steps:
      - uses: actions/checkout@v2
      - name: read the current version from the release.yaml
        id: current-release
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: .github/workflows/release.yaml
          version: env.version
      - run: echo ${{ steps.current-release.outputs.version }}
      - name: read latest version from the changelog
        id: next-release
        uses: mattwynne/changelog-action@v1.2
        with:
          args: latest
      - run: |
        echo current release: ${{ steps.current-release.outputs.version }}
        echo current release: ${{ steps.next-version.outputs.output }}
      # if the changelog shows a new release, go!
      # * update release.yaml
      # * ...