name: Pre-release

# Prepares a new release of the build image.
# 
# To trigger it, simply change the CHANGELOG.md file, replacing the
# "Unreleased" header with the header with the new release's 
# version number.
#
# The workflow will automatically prepare a pull request to the `release` branch.
#

on:
  push:
    branches: [automate-prerelase]
  pull_request:

jobs:

  versions:
    runs-on: ubuntu-latest
    name: Get version numbers
    outputs:
      released-version: ${{ steps.current-release.outputs.result }}
      next-version: ${{ steps.next-release.outputs.output }}
    steps:
      - uses: actions/checkout@v2
      - name: read the current version from the release.yaml
        id: current-release
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.env.version' '.github/workflows/release.yaml'
      - name: read latest version from the changelog
        id: next-release
        uses: mattwynne/changelog-action@v1.2
        with:
          args: latest
  
  update-release-yaml:
    runs-on: ubuntu-latest
    name: Update release.yaml
    needs: versions
    if: needs.versions.outputs.released-version != needs.versions.outputs.next-version
    env:
      released_version: needs.versions.outputs.released-version 
      next_version: needs.versions.outputs.next-version 
    steps:
      - uses: mikefarah/yq@master
        with:
          cmd: yq eval '.env.version = "$next-version"' --inplace .github/workflows/release.yaml
      - run: cat .github/workflows/release.yaml
      # # * ...