name: Pre-release

# Prepares a new release of the build image.
# 
# To trigger it, simply change the CHANGELOG.md file, replacing the
# "Unreleased" header with the header with the new release's 
# version number.
#
# The workflow will automatically prepare a pull request to the `release` branch.
#

on:
  push:
    branches: [automate-prerelase]
  pull_request:

jobs:
  update-release-yaml:
    runs-on: ubuntu-latest
    name: Update release.yaml

    steps:
      - uses: actions/checkout@v2
      - name: read the current version from the release.yaml
        id: current-release
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.env.version' '.github/workflows/release.yaml'
      - run: echo "released-version=${{ steps.current-release.outputs.result }}" >> $GITHUB_ENV
      - name: read latest version from the changelog
        id: next-release
        uses: mattwynne/changelog-action@v1.2
        with:
          args: latest
      - run: echo "next-version=${{ steps.next-release.outputs.output }}" >> $GITHUB_ENV
      - run: |
          echo current release: $released-version
          echo next release: $next-version
      # # if the changelog shows a new release, go!
      # - name: Update release.yaml
      #   if: $current-version != $next-version
      #   uses: mikefarah/yq@master
      #   with:
      #     cmd: yq eval '.env.version = "$next-version"' --inplace .github/workflows/release.yaml
      # - run: cat .github/workflows/release.yaml
      # # * ...