name: Pre-release

on:
  push:
    branches: [automate-prerelase]

jobs:
  update-release-yaml:
    runs-on: ubuntu-latest
    name: Update release.yaml

    steps:
      - uses: actions/checkout@v2
      - name: read the current version from the release.yaml
        id: current-release
        uses: @cumulusds@v0.0.0
        with:
          file: .github/workflows/release.yaml
          version: env.version
      - run: echo {{ steps.current-release.outputs.version }}
      # read latest version from the changelog
      # if the changelog shows a new release, go!
      # * update release.yaml
      # * ...