name: Pre-release

# Prepares a new release of the build image.
# 
# To trigger it, simply change the CHANGELOG.md file, replacing the
# "Unreleased" header with the header with the new release's 
# version number.
#
# The workflow will automatically prepare a pull request to the `release` branch.
#

on:
  push:
    branches: [main]

jobs:

  versions:
    runs-on: ubuntu-latest
    name: Get version numbers
    outputs:
      released-version: ${{ steps.current-release.outputs.result }}
      next-version: ${{ steps.next-release.outputs.output }}
    steps:
      - uses: actions/checkout@v2
      - name: read the current release version from git tags
        id: current-release
        run: |
          version_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          version=${version_tag/v/}
          echo "::set-output name=result::$version"
      - name: read latest version from the changelog
        id: next-release
        uses: mattwynne/changelog-action@v1.2
        with:
          args: latest
  
  create-release-pr:
    runs-on: ubuntu-latest
    name: Create Release PR
    needs: versions
    if: needs.versions.outputs.released-version != needs.versions.outputs.next-version
    env:
      next_version: ${{ needs.versions.outputs.next-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - run: git fetch origin main
      - run: git checkout main
      - run: git checkout release
      - run: git rebase main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: release
          branch: pre-release/${{ env.next_version }}
          title: "Release v${{ env.next_version }}"
          body: |
            Automated changed by [pre-release.yaml](https://github.com/cucumber/build/blob/main/.github/workflows/pre-release.yaml) GitHub action.

            See diff for details.
          team-reviewers: "@cucumber/build"