name: Release

on:
  push:
    branches: [release*]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Publish docker image
    environment: Release

    steps:
      - uses: actions/checkout@v2
      - name: Read version number
        run: echo "version"=$(cat VERSION) > $GITHUB_ENV
      - uses: actions-ecosystem/action-regex-match@v2
        id: version
        with:
          text: ${{ env.version }}
          regex: '\d+\.\d+\.\d+'
      - name: Check valid version
        if: steps.version.outputs.match == ''
        run: |
          echo "Invalid version: ${{ env.version }}"
          exit 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          labels: |
            version=${{ env.version }}
          tags: cucumber/cucumber-build:latest,cucumber/cucumber-build:${{ env.version }}
      - name: Tag the commit
        run: git tag v${{ env.version }} && git push --tags
